const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  loadData: () => ipcRenderer.invoke('data:load'),
  saveGames: (games) => ipcRenderer.invoke('data:save-games', games),
  saveSettings: (settings) => ipcRenderer.invoke('data:save-settings', settings),

  pickExe: () => ipcRenderer.invoke('pick:exe'),
  exeCandidates: (exePath) => ipcRenderer.invoke('game:exe-candidates', exePath),
  pickFolder: (title) => ipcRenderer.invoke('pick:folder', title),
  pickDll: () => ipcRenderer.invoke('pick:dll'),
  pickImage: () => ipcRenderer.invoke('pick:image'),
  scanLibrary: (options) => ipcRenderer.invoke('library:scan', options),
  streamlineVersions: () => ipcRenderer.invoke('streamline:versions'),

  frameGenVersions: () => ipcRenderer.invoke('framegen:versions'),
  frameGenState: (exePath) => ipcRenderer.invoke('framegen:state', exePath),
  frameGenSwap: (exePath, version) => ipcRenderer.invoke('framegen:swap', { exePath, version }),
  frameGenRestore: (exePath) => ipcRenderer.invoke('framegen:restore', exePath),
  frameGenMultiplier: (exePath) => ipcRenderer.invoke('framegen:multiplier', exePath),
  frameGenSetMultiplier: (payload) => ipcRenderer.invoke('framegen:setMultiplier', payload),
  rtxmfgState: (exePath) => ipcRenderer.invoke('rtxmfg:state', exePath),
  rtxmfgInstall: (payload) => ipcRenderer.invoke('rtxmfg:install', payload),
  rtxmfgRemove: (exePath) => ipcRenderer.invoke('rtxmfg:remove', exePath),

  injectorReadiness: (releaseFolder) => ipcRenderer.invoke('injector:readiness', { releaseFolder }),
  injectorSteamOption: (releaseFolder) => ipcRenderer.invoke('injector:steamOption', { releaseFolder }),
  injectorLaunch: (exePath, releaseFolder) => ipcRenderer.invoke('injector:launch', { exePath, releaseFolder }),

  optiFgReadiness: (exePath) => ipcRenderer.invoke('optifg:readiness', exePath),
  optiFgSet: (exePath, enabled) => ipcRenderer.invoke('optifg:set', { exePath, enabled }),
  optiFgChoose: (exePath, generator, startOn) => ipcRenderer.invoke('optifg:set', { exePath, generator, startOn }),
  optiFgLive: (exePath) => ipcRenderer.invoke('optifg:live', { exePath }),
  optiFgLiveSet: (exePath, values) => ipcRenderer.invoke('optifg:live-set', { exePath, ...values }),

  feederReadiness: (exePath) => ipcRenderer.invoke('feeder:readiness', exePath),
  feederMvProviders: () => ipcRenderer.invoke('feeder:mvProviders'),
  addonsForGame: (exePath) => ipcRenderer.invoke('addons:forGame', { exePath }),
  addonsInstall: (exePath, id) => ipcRenderer.invoke('addons:install', { exePath, id }),
  addonsRemove: (exePath, id) => ipcRenderer.invoke('addons:remove', { exePath, id }),
  addonsSetMvProvider: (exePath, mvProviderId, { licenseConfirmed = false } = {}) =>
    ipcRenderer.invoke('addons:setMvProvider', { exePath, mvProviderId, licenseConfirmed }),
  legacyDgVoodoo: (exePath, detected) => ipcRenderer.invoke('legacy:dgvoodoo', { exePath, detected }),
  legacyInstallHost32: (payload) => ipcRenderer.invoke('legacy:installHost32', payload),
  legacyMvProvider: (exePath) => ipcRenderer.invoke('legacy:mvProvider', { exePath }),
  legacySetMvProvider: (exePath, mvProviderId, { licenseConfirmed = false } = {}) =>
    ipcRenderer.invoke('legacy:setMvProvider', { exePath, mvProviderId, licenseConfirmed }),
  feederCheckUpdate: (exePath) => ipcRenderer.invoke('feeder:checkUpdate', exePath),
  feederConfirmProviderLicense: (providerId) => ipcRenderer.invoke('feeder:confirmProviderLicense', providerId),
  feederDeploy: (exePath, mvProviderId, options) => ipcRenderer.invoke('feeder:deploy', { exePath, mvProviderId, ...options }),
  dfcSupply: (sourcePath) => ipcRenderer.invoke('dfc:supply', sourcePath),
  dfcStatus: (exePath) => ipcRenderer.invoke('dfc:status', exePath),
  dfcSwitch: (exePath, to, nrDllPath) => ipcRenderer.invoke('dfc:switch', { exePath, to, nrDllPath }),
  dfcCfgRead: (exePath) => ipcRenderer.invoke('dfc:cfg-read', exePath),
  dfcCfgWrite: (exePath, edits) => ipcRenderer.invoke('dfc:cfg-write', { exePath, edits }),
  feederRemove: (exePath) => ipcRenderer.invoke('feeder:remove', exePath),
  feederOpenReShadeSetup: () => ipcRenderer.invoke('feeder:openReShadeSetup'),

  lumaUeReadiness: (exePath) => ipcRenderer.invoke('lumaue:readiness', { exePath }),
  lumaUeDeploy: (exePath, options) => ipcRenderer.invoke('lumaue:deploy', { exePath, ...options }),
  lumaUeRemove: (exePath) => ipcRenderer.invoke('lumaue:remove', { exePath }),
  lumaUeApplyAmdIntelWorkaround: (exePath) => ipcRenderer.invoke('lumaue:applyAmdIntelWorkaround', { exePath }),

  relimiterStatus: (exePath) => ipcRenderer.invoke('relimiter:status', exePath),
  relimiterSetTarget: (exePath, fps) => ipcRenderer.invoke('relimiter:set-target', { exePath, fps }),
  relimiterInstall: (exePath) => ipcRenderer.invoke('relimiter:install', exePath),
  relimiterRemove:(exePath) => ipcRenderer.invoke('relimiter:remove', exePath),
  losslessDetect: () => ipcRenderer.invoke('lossless:detect'),
  losslessEligibility: (exePath) => ipcRenderer.invoke('lossless:eligibility', exePath),
  losslessReadSettings: () => ipcRenderer.invoke('lossless:readSettings'),
  losslessWriteSettings: (xmlText) => ipcRenderer.invoke('lossless:writeSettings', xmlText),
  losslessLaunch: () => ipcRenderer.invoke('lossless:launch'),
  losslessRestart: () => ipcRenderer.invoke('lossless:restart'),
  losslessOpenStorePage: () => ipcRenderer.invoke('lossless:openStorePage'),
  losslessSetExePathInGameIni: (exePath, losslessExePath, gameTitle, profile = {}) => ipcRenderer.invoke('lossless:setExePathInGameIni', { exePath, losslessExePath, gameTitle, ...profile }),

  steamSearch: (term) => ipcRenderer.invoke('steam:search', term),
  steamSearchVersion: () => ipcRenderer.invoke('steam:searchVersion'),
  resolveBanner: (exePath, name) => ipcRenderer.invoke('banner:resolve', { exePath, name }),
  nameForExe: (exePath) => ipcRenderer.invoke('game:nameForExe', exePath),
  validateRelease: (folder) => ipcRenderer.invoke('release:validate', folder),
  validateNrDll: (filePath) => ipcRenderer.invoke('nrdll:validate', filePath),
  autoFetchNrDll: () => ipcRenderer.invoke('nrdll:autoFetch'),
  nrModelLatest: () => ipcRenderer.invoke('nrdll:latest'),
  bundledEngine: () => ipcRenderer.invoke('update:bundledEngine'),

  gameStatus: (exePath) => ipcRenderer.invoke('game:status', exePath),
  gameRoute: (exePath, detected) => ipcRenderer.invoke('game:route', { exePath, detected }),
  gpuInfo: () => ipcRenderer.invoke('gpu:info'),
  setApiOverride: (exePath, api) => ipcRenderer.invoke('game:setApiOverride', { exePath, api }),
  proxyInfo: (exePath) => ipcRenderer.invoke('game:proxyInfo', { exePath }),
  setProxyName: (exePath, proxy) => ipcRenderer.invoke('game:setProxyName', { exePath, proxy }),

  amdNrStatus: (exePath, api) => ipcRenderer.invoke('amdnr:status', { exePath, api }),
  amdNrLatest: () => ipcRenderer.invoke('amdnr:latest'),
  amdNrOpenReleasePage: () => ipcRenderer.invoke('amdnr:openReleasePage'),
  amdNrDeployNrModel: (exePath, options) => ipcRenderer.invoke('amdnr:deployNrModel', { exePath, ...options }),
  amdNrRunSetup: (exePath) => ipcRenderer.invoke('amdnr:runSetup', exePath),
  detectPath: (exePath) => ipcRenderer.invoke('game:detect-path', exePath),
  detectPathIfStale: (exePath, stored) => ipcRenderer.invoke('game:detect-path-if-stale', { exePath, stored }),
  installGame: (payload) => ipcRenderer.invoke('game:install', payload),
  syncGameIfStale: (payload) => ipcRenderer.invoke('game:sync-if-stale', payload),
  runSetup: (exePath) => ipcRenderer.invoke('game:run-setup', exePath),
  runUninstall: (exePath) => ipcRenderer.invoke('game:run-uninstall', exePath),
  uninstallPlan: (exePath) => ipcRenderer.invoke('game:uninstallPlan', exePath),
  openFolder: (exePath) => ipcRenderer.invoke('game:open-folder', exePath),
  launchGame: (exePath, launcher) => ipcRenderer.invoke('game:launch', { exePath, launcher }),
  gameLauncher: (exePath) => ipcRenderer.invoke('game:launcher', exePath),
  gameRunning: (exePath) => ipcRenderer.invoke('game:running', { exePath }),
  lastRun: (exePath) => ipcRenderer.invoke('game:lastRun', exePath),
  supportBundle: (exePath, detected) => ipcRenderer.invoke('game:supportBundle', { exePath, detected }),
  reportStatus: () => ipcRenderer.invoke('report:status'),
  reportSignIn: () => ipcRenderer.invoke('report:signin'),
  reportSignOut: () => ipcRenderer.invoke('report:signout'),
  reportPrepare: (payload) => ipcRenderer.invoke('report:prepare', payload),
  reportSend: (id) => ipcRenderer.invoke('report:send', { id }),
  reportDiscard: (id) => ipcRenderer.invoke('report:discard', { id }),
  gameHelp: (exePath, detected, fixesTried) => ipcRenderer.invoke('game:help', { exePath, detected, fixesTried }),
  gameHelpApply: (exePath, fixId) => ipcRenderer.invoke('game:help-apply', { exePath, fixId }),
  gameHelpAi: (exePath, detected, fixesTried) => ipcRenderer.invoke('game:help-ai', { exePath, detected, fixesTried }),
  onGameHelpAiText: (cb) => ipcRenderer.on('game:help-ai-text', (_evt, payload) => cb(payload)),
  probeGame: (exePath, launcher) => ipcRenderer.invoke('game:probe', { exePath, launcher }),
  probeFacts: (exePath) => ipcRenderer.invoke('game:probe-facts', { exePath }),
  onProbeProgress: (cb) => ipcRenderer.on('game:probe-progress', (_evt, payload) => cb(payload)),
  preflight: (exePath, detected) => ipcRenderer.invoke('game:preflight', { exePath, detected }),
  preflightFix: (exePath, fix) => ipcRenderer.invoke('game:preflight-fix', { exePath, fix }),
  verifyInstall: (exePath, launcher, detected) => ipcRenderer.invoke('game:verify', { exePath, launcher, detected }),
  onVerifyProgress: (cb) => ipcRenderer.on('game:verify-progress', (_evt, payload) => cb(payload)),
  openPath: (p) => ipcRenderer.invoke('shell:openPath', p),
  copyZipToClipboard: (zipPath) => ipcRenderer.invoke('report:copy-zip', zipPath),
  openExternal: (url) => ipcRenderer.invoke('shell:openExternal', url),
  pdPluginStatus: () => ipcRenderer.invoke('pdplugin:status'),
  pdPluginPick: () => ipcRenderer.invoke('pdplugin:pick'),
  pdPluginImport: (sourcePath) => ipcRenderer.invoke('pdplugin:import', { sourcePath }),

  confirmRemove: (gameName) => ipcRenderer.invoke('game:confirm-remove', gameName),
  removeForeign: (exePath) => ipcRenderer.invoke('game:removeForeign', exePath),
  cleanFolder: (folder) => ipcRenderer.invoke('game:cleanFolder', { folder }),

  cacheSteamBanner: (appid, fallbackImageUrl) => ipcRenderer.invoke('banner:cache-steam', { appid, fallbackImageUrl }),
  cacheUrlBanner: (id, imageUrl) => ipcRenderer.invoke('banner:cache-url', { id, imageUrl }),
  exeIconBanner: (exePath) => ipcRenderer.invoke('banner:exe-icon', exePath),
  gamesRunning: (exePaths) => ipcRenderer.invoke('games:running', exePaths),
  // A launch this app started is watched in main.js (launchwatch.js); an early exit or an
  // anti-cheat refusal comes back here. Restoring stays the user's click.
  onLaunchOutcome: (cb) => { ipcRenderer.on('game:launch-outcome', (_evt, notice) => cb(notice)); },
  safetyCheckInstalled: (exePath) => ipcRenderer.invoke('safety:check-installed', { exePath }),
  safetyDgVoodooQuarantine: (exePath) => ipcRenderer.invoke('safety:dgvoodoo-quarantine', { exePath }),
  openProtectionHistory: () => ipcRenderer.invoke('safety:open-protection-history'),
  dlssNrGet: (exePath) => ipcRenderer.invoke('dlssnr:get', exePath),
  dlssNrSet: (exePath, values) => ipcRenderer.invoke('dlssnr:set', { exePath, values }),

  // The break-away DLSS 5 panel (src/panelwindow.js). panelTargets is its own list rather than
  // loadData's, because it also says which game is running -- that is what it opens on.
  panelTargets: () => ipcRenderer.invoke('panel:targets'),
  panelTiming: (exePath) => ipcRenderer.invoke('panel:timing', exePath),
  panelMotion: (exePath) => ipcRenderer.invoke('panel:motion', exePath),
  panelLive: (exePath) => ipcRenderer.invoke('panel:live', exePath),
  panelLiveStop: (exePath) => ipcRenderer.invoke('panel:live-stop', exePath),
  panelClose: () => ipcRenderer.invoke('panel:close'),
  panelResetLayout: () => ipcRenderer.invoke('panel:reset-layout'),
  panelOpen: () => ipcRenderer.invoke('panel:open'),
  panelHotkeyState: () => ipcRenderer.invoke('panel:hotkeyState'),
  onPanelOpened: (cb) => { ipcRenderer.on('panel:opened', () => cb()); },
  onSettingsChanged: (cb) => { ipcRenderer.on('settings-changed', (_evt, settings) => cb(settings)); },
  importLocalBanner: (sourcePath) => ipcRenderer.invoke('banner:import-local', sourcePath),

  checkUpdate: (engine) => ipcRenderer.invoke('update:check', { engine }),
  engineList: () => ipcRenderer.invoke('engine:list'),
  engineForGame: (exePath) => ipcRenderer.invoke('engine:forGame', exePath),
  engineSetForGame: (args) => ipcRenderer.invoke('engine:setForGame', args),
  setGameEngine: (payload) => ipcRenderer.invoke('engine:setForGame', payload),
  installUpdate: (payload) => ipcRenderer.invoke('update:install', payload),
  checkManagerUpdate: () => ipcRenderer.invoke('update:checkManager'),
  openManagerReleasePage: () => ipcRenderer.invoke('update:openManagerReleasePage'),
  managerUpdateState: () => ipcRenderer.invoke('update:managerState'),
  managerUpdateCheck: () => ipcRenderer.invoke('update:managerCheck'),
  managerUpdateRestart: () => ipcRenderer.invoke('update:managerRestart'),
  managerUpdateDownload: () => ipcRenderer.invoke('update:managerDownload'),
  onManagerUpdate: (cb) => { ipcRenderer.on('manager-update', (_evt, state) => cb(state)); },
  onReportSignIn: (cb) => { ipcRenderer.on('report-signin', (_evt, result) => cb(result)); },

  engineHasKnownProfile: (exePath) => ipcRenderer.invoke('engine:hasKnownProfile', { exePath })
});
